apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-app
  namespace: dev # Ensure this namespace exists on your VM (kubectl create namespace dev)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
        - name: app
          image: rizwan441/production-app:TMP_SHA_TAG # Placeholder
          ports:
            - containerPort: 3000